config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :final_orders
  resources :order_details
  resources :products
  resources :order_items
  resources :carts

  
  root 'home#index'
  resources :companies, path: 'restoranlar'
  resources :cities, path: '', only: [:index, :show], :controller => 'home' do 
    resources :districts, path: '', only: [:show]
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :orders
end

app/models/city.rb
class City < ActiveRecord::Base
    extend FriendlyId
    friendly_id :name, :use => :slugged
    
    has_many :companies
    has_many :districts
end

app/models/company.rb
class Company < ActiveRecord::Base
    extend FriendlyId
    friendly_id :url_path, :use => :slugged
    
    belongs_to :city
    belongs_to :district
    has_many :product
    
    scope :food_type, -> (food_type) { where food_type: food_type }
    scope :delivery, -> (delivery) { where delivery: delivery } 
end

app/models/district.rb
class District < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  
  belongs_to :city
  has_many :companies
end

app/models/final_order.rb
class FinalOrder < ActiveRecord::Base
    has_many :order
    has_many :order_item
end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_items
	belongs_to :receipt
	belongs_to :order
	
	before_save :set_subtotal

	def subtotal
		order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
	end

	private
		def set_subtotal
			self[:subtotal] = subtotal
		end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :product
	belongs_to :final_order

	before_save :set_unit_price
	before_save :set_total_price

	def unit_price
		if persisted?
			self[:unit_price]
		else
			product.discounted_price
		end
	end

	def total_price
		unit_price * quantity
	end

	private

		def set_unit_price
			self[:unit_price] = unit_price
		end

		def set_total_price
			self[:total_price] = quantity * set_unit_price
		end
end

app/models/product.rb
class Product < ActiveRecord::Base
     belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @order_items = current_order.order_items
  end
  
  def show
    @cart = Cart.find(params[:id])
  end
	
  def new
    @cart = Cart.new
  end
  
  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to carts_path
    else
      render 'new'
    end
  end
  
  def update
    @cart = Cart.new(cart_params)
    if @cart.update_attributes(cart_params)
      redirect_to carts_path
    else
      render 'edit'
    end
  end

  private
  def cart_params
    params.require(:cart).permit(:order_item_id, :order_id, :order_message, :delivery, :payment_method)
  end
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    
   #scopes
   @companies = @companies.food_type(params[:food_type]) if params[:food_type].present?
   @companies = @companies.delivery(true) if params[:delivery].present?
   
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @Companies = Company.friendly.find(params[:id])
    @Products = Product.where(company_id: @company.id)
    @order_item = current_order.order_items.new
  end

  # GET /companies/new
  def new
    @company = Company.new
    @cities = City.all
    @districts = District.all
  end

  # GET /companies/1/edit
  def edit
    @cities = City.all
    @districts = District.all
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Firma başarıyla oluşturuldu.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Firma başarıyla güncellendi.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Firma başarıyla silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :manager, :address, :company_phone, :manager_phone, :tax_number, :food_type, :email, :rate, :delivery, :city_id, :district_id, :url_path)
    end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  
  def index
  end
  
 def show
   @cities = City.all
   @city = City.friendly.find(params[:city_id])
   @districts = District.all
   @district = District.friendly.find(params[:id])
   @companies = @district.companies
   
   #scopes
   @companies = @companies.food_type(params[:food_type]) if params[:food_type].present?
   @companies = @city.companies.delivery(true) if params[:delivery].present?
 end
 
 private
    # Use callbacks to share common setup or constraints between actions.
    def find_district
      @district = District.friendly.find(params[:id])
    end
 
    def district_params
      params.require(:district).permit(:name, city_id, :slugged)
    end

  def new
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @cities = City.all
    @companies = Company.all
  end
  
 def show
   @city = City.friendly.find(params[:id])
   @companies = @city.companies
   @districts = District.all
   
   #scopes
   @companies = @companies.food_type(params[:food_type]) if params[:food_type].present?
   @companies = @city.companies.delivery(true) if params[:delivery].present?
   
 end
 
 private
    # Use callbacks to share common setup or constraints between actions.
    def find_city
      @city = City.friendly.find(params[:id])
    end
 
    def city_params
      params.require(:city).permit(:name, :included, :slug)
    end

  def new
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path    
  end

  private
    def product_params
      params.require(:product).permit(:company_id, :title, :normal_price, :discounted_price, :remaining_stock, :discounted_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_order
		if !session[:order_id].nil?
			Order.find(session[:order_id])
		else
			Order.new
		end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/final_orders_helper.rb
module FinalOrdersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<%= form_for carts_path do |f| %>

<% if @order_items.size>0 %>

		<table width="100%">	
			
	<% @order_items.each do |item| %>
	
				<tr>
					<td width="7%">
						
							<%= form_for(item, remote: true) do |f| %>
							<div class="input-group input-group-sm">
								<%= f.hidden_field :product_id, value: item.product.id %>
								<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control smInput' %>
								<!-- <span class="input-group-btn smInput">
									<%#= link_to "Güncelle", class: 'btn btn-secondary', url_for(:back) %>
								</span> -->
								<div class="form-group">
								</div>
								</div>
							<% end %>
							</td>
					<td width="75%">
						<p class="card-text ml-5" style="padding-left:20px;" >&nbsp; <%= link_to "Sil", item, method: :delete, remote: true, class: 'btn btn-danger' %> <%= item.product.title %> </p>
					</td>
					<td width="20%" class="sagaHizala" class="sagaHizala">
						<p class="card-text"><del><%= item.product.normal_price %> ₺</del><b> | <span id="fiyat-<%= item.product.id %>"><%= item.product.discounted_price %></span> ₺</b></p>
					
					</td>
				</tr>
	
	<% end %>
	</table> 
<% else %>
	
<% end %>

<center><b><span class="cart"><p><%= current_order.order_items.size %> Adet ürün</p>
				     	<p>Toplam Tutar: <%= current_order.subtotal %> ₺</p></span></b></center>
  			
  			<label for="shopping-cart-payment" class="col-form-label"><b>Ödeme bilgileri:</b></label><br>
			<table width="100%">
			<tr><td><%= radio_button_tag(:payment_method, "nakit", checked = true) %><%= label_tag(:payment_method_nakit, " Nakit ") %>
			</td><td><%= radio_button_tag(:payment_method, "kart") %><%= label_tag(:payment_method_nakit, " Kredi / Banka Kartı ") %> </td><td>
        	<%= check_box_tag(:delivery) %><%= label_tag(:delivery, " Adrese teslimat") %>
        	</td></tr>	
			</table>
			  
          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Sipariş notu:</b></label>
            <%= f.text_area :order_message, class: 'form-control', placeholder: 'Restorana iletmek istediğiniz bir talebiniz varsa buraya yazabilirsiniz.' %>
          </div>
          
		<% if @order_items.size>0 %>
			<center><%= f.submit "SİPARİŞİ ONAYLA", class: 'btn btn-success' %></center>
        <% else %> 
          <center><button class="btn btn-success" disabled>SİPARİŞİ ONAYLA</button></center>
       	<% end %>
        </form>
        </div>
		</div>
		
</div>
</div>
<% end %>

app/views/carts/index.html.erb
<div class="container-fluid pt-5">
    <div class="row mt-5"> 
<%= render "layouts/shopping_cart" %>

<div class="col-md-8 offset-md-1 profilSayfasi">
<div class="card" style="padding: 30px; margin: 20px;">
	<label for="shopping-cart-items" class="col-form-label"><center><b>Sepetinizdeki Ürünler</b></center></label>
                        <div class="cart_item">
<%= render "carts/cart_item" %>        
  	    </div>
  	    </div>

app/views/carts/show.html.erb
<div class="container-fluid pt-5">
    <div class="row mt-5"> 
<%= render "layouts/shopping_cart" %>

<div class="col-md-8 offset-md-1 profilSayfasi">
<div class="card" style="padding: 30px; margin: 20px;">
	<label for="shopping-cart-items" class="col-form-label"><center><b>Sepetinizdeki Ürünler</b></center></label>
                        <div class="cart_item">
<%= render "carts/cart_item" %>        
  	    </div>
  	    </div>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
<div class="col-lg-6 col-md-6 col-sm-12">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.select(:city_id, @cities.all.collect {|a| [a.name, a.id] }) %>
  </div>
  <div class="field">
    <%= f.label :district_id %><br>
    <%= f.select(:district_id, @districts.all.collect {|d| [d.name, d.id] }) %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :company_phone %><br>
    <%= f.text_field :company_phone %>
  </div>
  <div class="field">
    <%= f.label :url_path %><br>
    <%= f.text_field :url_path %>
  </div>
    
</div>
<div class="col-lg-6 col-md-6 col-sm-12">
  
  <div class="field">
    <%= f.label :manager_phone %><br>
    <%= f.text_field :manager_phone %>
  </div>
  <div class="field">
    <%= f.label :tax_number %><br>
    <%= f.text_field :tax_number %>
  </div>

  <div class="field">
  <%= f.label :food_type %><br>
  <%= f.select :food_type, [['Çiğ Köfte'],['Cafe'],['Deniz Mahsülleri'],['Ev Yemekleri'],['Fast Food'],['Kahvaltı & Börek'],['Pizza'],['Tatlı']] %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :delivery %><br>
    <%= f.check_box :delivery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div><!-- /col -->
</div><!-- /row -->
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid"> 
	<div class="row mt-3 h-100">
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 my-auto">
		</div>
		<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
			<p class="shoppingMenuBaslik">CazipYemek platformundaki tüm işletmeler <span style="font-size: 12px"><a href="/">Değiştir</a></span></p>
			<p>Aşağıdaki filtreleme seçeneklerinden aradığınız mutfak türünü ve size uygun ödeme ve hizmet seçeneklerinden istediğinizi seçerek sıralama yapabilirsiniz. </p>
			<div class="bd-example">
				<label>Filtrele: </label>
			  <div class="btn-group">
			    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sırala</button>
			    <div class="dropdown-menu">
			      <a class="dropdown-item" href="#">A'dan Z'ye</a>
			      <a class="dropdown-item" href="#">Puana Göre</a>
			    </div>
			  </div><!-- /btn-group -->
			  <div class="btn-group">
			    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mutfak Türü</button>
			    <div class="dropdown-menu">
			      <a class="dropdown-item" href="?food_type=Çiğ+Köfte">Çiğ Köfte</a>
			      <a class="dropdown-item" href="?food_type=Cafe">Cafe</a>
			      <a class="dropdown-item" href="?food_type=Deniz+mahsülleri">Deniz Mahsülleri</a>
			      <a class="dropdown-item" href="?food_type=Ev+Yemekleri">Ev Yemekleri</a>
            <a class="dropdown-item" href="?food_type=Fast+Food">Fast Food</a>
            <a class="dropdown-item" href="?food_type=Kahvaltı+%26+Börek">Kahvaltı & Börek</a>
			      <a class="dropdown-item" href="?food_type=Pizza">Pizza</a>
			      <a class="dropdown-item" href="?food_type=Tatlı">Tatlı</a>
			      			      			      			      			      
			    </div>
			  </div><!-- /btn-group -->
			  <div class="btn-group">
			    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ödeme Şekli</button>
			    <div class="dropdown-menu">
			      <a class="dropdown-item" href="#">Nakit</a>
			      <a class="dropdown-item" href="#">Banka Kartı</a>
			      <a class="dropdown-item" href="#">Ticket Kart</a>
			      <a class="dropdown-item" href="#">Ticket Çek</a>
			      <a class="dropdown-item" href="#">Sodexo Kart</a>
			      <a class="dropdown-item" href="#">Sodexo Çek</a>
			      <div class="dropdown-divider"></div>
			      <a class="dropdown-item" href="#">Online Ödeme</a>
			    </div>
			  </div><!-- /btn-group -->
			  			  <div class="btn-group">
			    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hizmet Türü</button>
			    <div class="dropdown-menu">
			      <a class="dropdown-item" href="/restoranlar">Tümü</a>
			      <a class="dropdown-item" href="?delivery=true">Adrese Teslimat</a>
			    </div>
			  </div><!-- /btn-group -->
			</div><!--  /fitreler  -->
		</div>
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 my-auto"></div>
	</div>
</div>
<hr> <!-- Restoranlar sayfası üst kalıcı menüsü burada bitiyor -->


<table class="table table-hover">
  <thead>
    <tr>
      <th>Restoran</th>
      <!--<th>Manager</th>-->
      <th>Şehir</th>
      <th>Bölge</th>
      <!--<th>Adres</th>-->
      <!--<th>Company phone</th>-->
      <!--<th>Manager phone</th>-->
      <!--<th>Tax number</th>-->
      <th>Mutfak türü</th>
      <!--<th>Email</th>-->
      <th>Puan</th>
      <th>Adrese Teslimat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <!--<td><%= company.manager %></td>-->
        <td><%= company.city.name %></td>
        <td><%= company.district.name %></td>
        <!--<td><%= company.address %></td>-->
        <!--<td><%= company.company_phone %></td>-->
        <!--<td><%= company.manager_phone %></td>-->
        <!--<td><%= company.tax_number %></td>-->
        <td><%= company.food_type %></td>
        <!--<td><%= company.email %></td>-->
        <td><%= company.rate %></td>
        <td><%= company.delivery ? "var" : "yok" %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Company', new_company_path %>
<% end <%></%>

app/views/companies/new.html.erb
<div class="container">
    <h1>Yeni Firma Ekle</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'İptal', companies_path %>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="container-fluid"> 
	<div class="row mt-3 h-100">
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 my-auto">
			<img src="../img/shopping.png" class="rounded-circle d-block mx-auto my-auto" width="100" data-toggle="modal" data-target="#sepetModal" data-whatever="@mdo" >
		</div>
		<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
			<p class="shoppingMenuBaslik"> <%= @company.name %> işletmesinin indirimli menüleri <span style="font-size: 12px"><a href="/">Değiştir</a></span></p>
			<p>Aşağıdaki menülerden istediğiniz miktarı girip <span style="color: black; border: 1px solid black; border-radius: 5px;">&nbsp;+&nbsp;</span> butonuna basarak sepetinize ekleyebilirsiniz. </p>
		</div>
	</div>
</div>  /restor fixed menu-->

<div class="container-fluid mt-3">
	<div class="row"> 
		<div class="profilHeader"></div>
		
		<%= render "layouts/shopping_cart" %>
	
		<div class="col-md-8 offset-md-1 profilSayfasi profilMobile">
			<table width="100%" class="mobiletable">
			<tr>
				<td>	
					<h3 class="menuItems"><%= @company.name %></h3>
					<p class="menuHour"> <%= @Products.first.try(:discounted_time) %> </p>
				</td>
				<td class="sagaHizala">
					<img src="../img/star.png">
					<p class="restoranPuan"><%= @company.rate %></p>
				</td>
			</table>
<br>
	
			<table width="100%">
				<tr>
					<th>
						<h4>İndirimli Ürünler: </h4>
					</th>
					<th width="15%" class="sagaHizala">
						Fiyat
					</th>
				</tr>
			</table>
			<table width="100%">
						<% @Products.each do |product| %>	
				<tr>
					<td width="13%">
						
							<%= form_for(@order_item, remote: true) do |f| %>
							<div class="input-group input-group-sm">
								<%= f.hidden_field :product_id, value: product.id %>
								<%= f.text_field :quantity, value: 1, min: 1, class: 'form-control smInput' %>
								<span class="input-group-btn smInput">
									<%= f.submit "+", class: 'btn btn-secondary' %>
								</span>
								<div class="form-group">
								</div>
								</div>
							<% end %>
							
					</td>
					<td>
						<p class="card-text ml-4" id="urun-<%= product.id %>">&nbsp;<%= product.title %></p>
					</td>
					<td class="sagaHizala" class="sagaHizala">
						<p class="card-text"><del><%= product.normal_price %> ₺</del><b> | <span id="fiyat-<%= product.id %>"><%= product.discounted_price %></span> ₺</b></p>
					</td>
				</tr>
<% end %>

			</table> 
			<br>
			<!--
			<div class="card" style="padding: 30px;">
			            <label for="shopping-cart-items" class="col-form-label"><b>Yorumlar (10)</b></label><hr>
  			
				<p><b>Siri:</b> <p style="margin-left: 15px;"> <span style="background-color: orange; color: white;  border: 1px solid black; border-radius: 5px;">&nbsp;5&nbsp;</span> Salatası çok tazeydi, güzeldi.</p><hr>
				<p><b>Alexa: </b><p style="margin-left: 15px;"> <span style="background-color: orange; color: white;  border: 1px solid black; border-radius: 5px;">&nbsp;5&nbsp;</span> Sipariş hızlı geldi, güzeldi.</p>
	
			  
        </div>
		</div><!-- col-md-8 -->


						<!--<p style="margin-top: 10px; margin-left: 30px;"><span style="background-color: orange; color: white;  border: 1px solid black; border-radius: 5px;">&nbsp;4&nbsp;</span> Alexa <p style="margin-left: 30px;"> Salatası çok tazeydi, güzeldi.</p>-->
	

</div><!-- /row -->
</div><!-- /container-fluid-->
<br>






<!-- sepet popup -->

<div class="modal fade" id="sepetModal" tabindex="-1" role="dialog" aria-labelledby="sepetModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="sepetModalLabel">Sepetiniz</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="shopping-cart-items" class="col-form-label"><b>Sepetinizdeki ürünler:</b></label>
            <!-- <p id="urunler">Sepetinize henüz bir ürün eklemediniz.</p> -->
						<ul id="sec" class="list-group list-group-flush" >
  						</ul>          
  						<center><b><p id="toplam">Toplam Tutar: 0 ₺</p></b></center>
  			
  			<label for="shopping-cart-payment" class="col-form-label"><b>Ödeme bilgileri:</b></label><br>
			<table width="100%">
			<tr><td><input type="radio" name="odeme" aria-label="nakit" checked> Nakit 
			</td><td><input type="radio" name="odeme" aria-label="kart"> Banka/kredi kartı </td><td><% if @company.delivery == true %>
        	<input type="checkbox" aria-label="siparis" > Adrese teslim
        	<% end %></td></tr>	
			</table>
			  
  					</div>
          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Sipariş notu:</b></label>
            <textarea class="form-control" id="message-text" placeholder="Restorana iletmek istediğiniz bir talebiniz varsa buraya yazabilirsiniz."></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">İptal</button>
        <button type="button" class="btn btn-primary">Sepeti Onayla</button>
      </div>
    </div>
  </div>
</div>



<script>
var toplam = 0;
	function urunEkle(clicked_id){
	  var adet = document.getElementById("adet-"+clicked_id).value;
	  var urun = document.getElementById("urun-"+clicked_id).textContent;
	  var fiyat = document.getElementById("fiyat-"+clicked_id).textContent;
	  
	  //document.getElementById("urunler").innerHTML = adet + urun + " - " + fiyat*adet + " ₺";
	  
      var yenielement = document.createElement("p");
      var icerik = document.createTextNode(adet + urun + " - " + fiyat*adet + " ₺");
      yenielement.appendChild(icerik);
      var sec = document.getElementById("sec");
      sec.appendChild(yenielement);
      toplam = toplam + fiyat*adet
      document.getElementById("toplam").innerHTML = "Toplam tutar: " + toplam + " ₺";
	}
</script>



<% if user_signed_in? %>


<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
<% end %>

app/views/products/edit.html.erb
<h3>Update product</h3>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="container">
<h1>Products</h1>

<%= link_to "New product", new_product_path %>

<div>
	<table class="table">
		<thead>
			<tr>
				<th>Firma id</th>
				<th>Ürün adı</th>
				<th>Normal fiyat</th>
				<th>İndirimli fiyat</th>
				<th>Kalan Stok</th>
				<th>İndirimli saatler</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.company_id %></td>
					<td><%= product.title %></td>
					<td><%= product.normal_price %></td>
					<td><%= product.discounted_price %></td>
					<td><%= product.remaining_stock %></td>
					<td><%= product.discounted_time %></td>
					
					<td>
						<%= link_to "Edit", edit_product_path(product) %>
						<%= link_to "Delete", product_path(product), method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
</div>