config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :final_orders
  resources :order_details
  resources :products
  resources :order_items
  resources :carts

  
  root 'home#index'
  resources :companies, path: 'restoranlar'
  resources :cities, path: '', only: [:index, :show], :controller => 'home' do 
    resources :districts, path: '', only: [:show]
  end

end

app/models/final_order.rb
class FinalOrder < ActiveRecord::Base
    has_many :order
    has_many :order_item
end

app/controllers/final_orders_controller.rb
class FinalOrdersController < ApplicationController
  before_action :set_final_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :show, :create]

  # GET /final_orders
  # GET /final_orders.json
  def index
    @final_orders = FinalOrder.all
    @orders = Order.all
    @order_items = OrderItem.all
    #@Products = Product.where(company_id: @company.id)
  end

  # GET /final_orders/1
  # GET /final_orders/1.json
  def show
    @final_orders = FinalOrder.find(params[:id])
    @order_items = OrderItem.where(:id => @final_orders.order_item_id)
  end

  # GET /final_orders/new
  def new
    @final_order = FinalOrder.new
    @order_items = current_order.order_items
  end

  # GET /final_orders/1/edit
  def edit
  end

  # POST /final_orders
  # POST /final_orders.json
  def create
    @final_order = FinalOrder.new(final_order_params)

    respond_to do |format|
      if @final_order.save
        format.html { redirect_to @final_order, notice: 'Siparişiniz alındı. İşletmenin profilinde yazan indirimli saatlerde ürününüzü teslim alabilirsiniz.' }
        format.json { render :show, status: :created, location: @final_order }
      else
        format.html { render :new }
        format.json { render json: @final_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /final_orders/1
  # PATCH/PUT /final_orders/1.json
  def update
    respond_to do |format|
      if @final_order.update(final_order_params)
        format.html { redirect_to @final_order, notice: 'Final order was successfully updated.' }
        format.json { render :show, status: :ok, location: @final_order }
      else
        format.html { render :edit }
        format.json { render json: @final_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /final_orders/1
  # DELETE /final_orders/1.json
  def destroy
    @final_order.destroy
    respond_to do |format|
      format.html { redirect_to final_orders_url, notice: 'Final order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_final_order
      @final_order = FinalOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def final_order_params
      params.require(:final_order).permit(:order_item_id, :order_id, :order_message, :delivery, :payment_method, :name, :address, :phone)
    end
end

app/helpers/final_orders_helper.rb
module FinalOrdersHelper
end

app/views/final_orders/_form.html.erb
<%= simple_form_for(@final_order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  
  <% if @order_items.size>0 %>

		<table width="100%">	
			
	<% @order_items.each do |item| %>
	
				<tr>
					<td width="7%">
							<div class="input-group input-group-sm">
							  <%= f.hidden_field :order_item_id, value: item.id %>
							  <%= f.hidden_field :order_id, value: item.order_id %>
								<%#= f.hidden_field :product_id, value: item.product.id %>
								<%= item.quantity.to_i %> adet
								<!-- <span class="input-group-btn smInput">
									<%#= link_to "Güncelle", class: 'btn btn-secondary', url_for(:back) %>
								</span> -->
								<div class="form-group">
								</div>
								</div>
														</td>
					<td width="75%">
						<p class="card-text ml-5" style="padding-left:20px;" >&nbsp; <%= link_to "Sil", item, method: :delete, remote: true, class: 'btn btn-danger' %> <%= item.product.title %> </p>
					</td>
					<td width="20%" class="sagaHizala" class="sagaHizala">
						<p class="card-text"><del><%= item.product.normal_price %> ₺</del><b> | <span id="fiyat-<%= item.product.id %>"><%= item.product.discounted_price %></span> ₺</b></p>
					
					</td>
				</tr>
	
	<% end %>
	</table> 
<% else %>
	
<% end %>

<center><b><span class="cart"><p><%= current_order.order_items.size %> Adet ürün</p>
				     	<p>Toplam Tutar: <%= current_order.subtotal %> ₺</p></span></b></center>
  			
  			<label for="shopping-cart-payment" class="col-form-label"><b>Ödeme bilgileri:</b></label><br>
			<table width="100%">
			<tr><td><%= f.radio_button :payment_method, "nakit", :checked => true %><%= label_tag(:payment_method_nakit, " Nakit ") %>
			</td><td><%= f.radio_button :payment_method, "kredi veya banka karti" %><%= label_tag(:payment_method_nakit, " Kredi / Banka Kartı ") %> </td><td>
        	<!--<%#= f.check_box :delivery %><%#= label_tag(:delivery, " Adrese teslimat") %>
        	</td>--></tr>	
			</table>
			  
          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Sipariş notu:</b></label>
            <%= f.text_area :order_message, class: 'form-control', placeholder: 'Restorana iletmek istediğiniz bir talebiniz varsa buraya yazabilirsiniz.' %>
          </div>

          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Adınız ve Soyadınız:</b></label>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Siparişinizi alırken sorulacak' %>
          </div>

<!--          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Adres:</b></label>
            <%#= f.text_area :address, class: 'form-control', placeholder: 'Adresi eksiksiz yazmanız ve çevrenizdeki bilinen yerlerle tanımlamanız önemli.' %>
          </div>
-->          
          <div class="form-group">
            <label for="message-text" class="col-form-label"><b>Telefon:</b></label>
            <%= f.text_field :phone, class: 'form-control', placeholder: 'Herhangi bir aksaklıkta iletişime geçebileceğimiz bir telefon numarası giriniz' %>
          </div>
          
		<% if @order_items.size>0 %>
			<center><%= f.submit "SİPARİŞİ ONAYLA", class: 'btn btn-success' %></center>
        <% else %> 
          <center><button class="btn btn-success" disabled>SİPARİŞİ ONAYLA</button></center>
       	<% end %>
        </form>
        </div>
		</div>
		
</div>
</div>
<% end %>

app/views/final_orders/edit.html.erb
<h1>Editing Final Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @final_order %> |
<%= link_to 'Back', final_orders_path %>

app/views/final_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Final Orders</h1>

<table border="1">
  <thead>
    <tr>
      <th>Sipariş id</th>
      <th>Order item</th>
      <th>Order</th>
      <th>Sipariş notu</th>
      <th>Sipariş</th>
      <th>Ödeme Yöntemi</th>
      <th>Ad Soyad</th>
      <th>Telefon</th>
      <th>Oluşturuldu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @final_orders.each do |final_order| %>
      <tr>
        <td><%= final_order.id %></td>
        <td><%= final_order.order_item_id %></td>
        <td><%= final_order.order_id %></td>
        <td><%= final_order.order_message %></td>
        <td><%= final_order.delivery %></td>
        <td><%= final_order.payment_method %></td>
        <td><%= final_order.name %></td>
        <td><%= final_order.phone %></td>
        <td><%= final_order.created_at %></td>
        <td><%= link_to 'Show', final_order %></td>
        <td><%= link_to 'Edit', edit_final_order_path(final_order) %></td>
        <td><%= link_to 'Destroy', final_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Final order', new_final_order_path %>

app/views/final_orders/new.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<div class="container-fluid pt-5">
    <div class="row mt-5"> 
<%= render "layouts/shopping_cart" %>

<div class="col-md-8 offset-md-1 profilSayfasi">
<div class="card" style="padding: 30px; margin: 20px;">
	<label for="shopping-cart-items" class="col-form-label"><center><b>Sepetinizdeki Ürünler</b></center></label>
                        <div class="cart_item">
<%#= render "carts/cart_item" %>        
<%= render 'form' %>


  	    </div>
  	    </div>

<% if user_signed_in? %>
<%= link_to 'Tüm siparişleri görüntüle', final_orders_path %>
<% end %> 

app/views/final_orders/show.html.erb
<% if user_signed_in? %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Order item:</strong>
  <%= @final_order.order_item_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @final_order.order_id %>
</p>

<p>
  <strong>Order message:</strong>
  <%= @final_order.order_message %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @final_order.delivery %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @final_order.payment_method %>
</p>

<%= link_to 'Edit', edit_final_order_path(@final_order) %> |
<%= link_to 'Back', final_orders_path %>
<% end %>

<center><h2> Siparişiniz alınmıştır. İndirimli saatler içerisinde işletmeye giderek isminizi söyleyin ve siparişinizi alın</h2></center>